### ISSUE TITLE
Espresso stops working when first showing a dialog, then a second one on top after finishing the second one.

### ISSUE THREAD

**Issue by mobilekosmos** [android/android-test#630]
### Description
Espresso stops working when first showing a dialog, then a second one on top, after finishing the second one.

### Steps to Reproduce
Run the test here: https://github.com/mobilekosmos/EspressoDialogsIssue/tree/master/app/src/androidTest/java/com/issues/espressoidling

### Expected Results
onView should find the view

### Actual Results
onView doesn't find anything with a timeout. Removing the second dialog solves the problem, so it seems that something doesn't get updated internally when returning back to the first dialog.

### AndroidX Test and Android OS Versions
All Android versions.
androidTestImplementation 'androidx.test.ext:junit:1.1.1'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
implementation 'androidx.test.espresso:espresso-idling-resource:3.1.1'
androidTestImplementation("androidx.test.espresso:espresso-intents:3.2.0")

### Link to a public git repo demonstrating the problem:
https://github.com/mobilekosmos/EspressoDialogsIssue
https://github.com/mobilekosmos/EspressoDialogsIssue/tree/master/app/src/androidTest/java/com/issues/espressoidling

**Comment by hoisie** [comment]
I believe the problem is that the test is missing a call to Espresso.onIdle(). When Espresso.onIdle() is called it waits for all pending idling resources to complete.

**Comment by hoisie** [comment]
Also I would recommend disabling animations during your tests. Animations can wreak havoc on view assertions.

**Comment by mobilekosmos** [comment]
Animations are disabled, and about the idle,  you are only assuming I suppose? I debugged this of course for days, onView waits 10 seconds where nothing happens, the second dialog in the attached example runs only 2 seconds.

**Comment by hoisie** [comment]
In the example you uploaded, the 2nd dialog (the one titled "Delay" is displayed at t=2 seconds and dismissed at t=15 seconds, so it is shown for 13 seconds:

https://github.com/mobilekosmos/EspressoDialogsIssue/blob/master/app/src/main/java/com/issues/espressoidling/MainActivity2.kt#L30-L43

I am not assuming about Espresso.onIdle, it makes the test pass:
```
--- a/app/src/androidTest/java/com/issues/espressoidling/MainActivity2Test.kt
+++ b/app/src/androidTest/java/com/issues/espressoidling/MainActivity2Test.kt
@@ -45,6 +45,7 @@ class MainActivity2Test {
             Assert.assertTrue(scenario.getState() == Lifecycle.State.RESUMED)
             Log.d("+++", "0")
             IdlingRegistry.getInstance().register(mIdlingResource)
+            Espresso.onIdle()
             Log.d("+++", "3")
             // TOFIX: Espresso doesn't find anything and we get the timeout exception.
             Espresso.onView(withText("OK")).check(ViewAssertions.matches(ViewMatchers.isDisplayed()))
```

**Comment by mobilekosmos** [comment]
Espresso.onIdle() didn't change anything on my side!

**Comment by mobilekosmos** [comment]
And, yes, I was wrong, the second dialog is shown 13 seconds, but AFTER that onView is executed and at this point onView waits for 10 seconds and then you get "Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds."

**Comment by TWiStErRob** [comment]
@mobilekosmos this works around the problem too:
```kotlin
window.decorView.post {
    // We're in the UI thread already, but wait a bit more to let the dialog dismiss properly?!
    // Note: `runOnUiThread` wouldn't work (see source code), need to explicitly `post` on a View.
    espressoTestIdlingResource.decrement();
}
```

@hoisie I don't think it's appropriate in this context to close an issue with "call `Espresso.onIdle`", as the main selling point of `onView....check` is that it includes that logic and waits for things. To me it looks like @mobilekosmos uses `CountingIdlingResource` and Espresso the way it was designed.

@brettchabot From the above workaround I think there's a problem in Espresso here. Something like *"if the idling resource gets idle in the same UI thread frame where the currently active root disappears, Espresso picks the disappearing root, because it was topmost at that point or fails to wait for some other reason"*. I can't prove this because just attaching the debugger makes the test pass (and also the sources don't match Espresso .class files), but that's my strongest hunch based on code.

**Comment by mobilekosmos** [comment]
Right, and Espresso.onIdle() isn't even recommended to be used in normal unit tests, anyways, as already noted it didn't even worked as a solution, so I'm not sure this was even tested, and then already closed?

**Comment by TWiStErRob** [comment]
`onIdle()` passed it for me, I tried twice; it could be that it just makes it flaky though with higher chance of passing. (As opposed to very likely/almost consistently failing.)

**Comment by mobilekosmos** [comment]
It doesn't matter how oftern on my side it doesn't work, trying with Pixel 3a and Android R.

**Comment by hoisie** [comment]
I am still unclear what the issue is. Please clarify if there is any misunderstanding:

1) During MainActivity2 creation, the first dialog is displayed immediately, the idling resource is initialized an incremented.
2) In the test, after MainActivity2 is launched, the test registers the idling resource and starts the onView assertion.
3) After 10 seconds, the onView assertion times out.
4) Although the test has failed at this point, at t=13 the idling resource is released.

So the expectation is that the onView should wait until t=13 for the idling resource to be released?

**Comment by hoisie** [comment]
I think I see the issue -- the 15 second dialog dismissal was a little confusing. After changing the dismissal timeout to something smaller, like 5 seconds, the timeout error was still there.

**Comment by hoisie** [comment]
Adding `inRoot(isDialog())` seemed to work for me. I believe Espresso is confused because there are multiple Windows (one for each Dialog/Alert).

```      Espresso.onView(withText("OK")).inRoot(isDialog()).check(ViewAssertions.matches(ViewMatchers.isDisplayed()))
```

**Comment by mobilekosmos** [comment]
So can actually somebody open this issue again? The issue is still there, isn't it?

**Comment by mobilekosmos** [comment]
"I believe Espresso is confused because there are multiple Windows" What do you mean? onView is executed after the second dialog disappears, so there is only one dialog at that moment?
